"""15 realistic mock findings for testing CLI, scorer, and report without real analyzers."""

from vibe_check.models.finding import Category, Finding, Severity


MOCK_FINDINGS = [
    # ── SECRETS (2) ────────────────────────────────────────────────
    Finding(
        title="Hardcoded AWS Access Key",
        severity=Severity.CRITICAL,
        category=Category.SECRET,
        file="app.py",
        line=14,
        description="AWS access key ID found hardcoded in source: AKIAIOSFODNN7EXAMPLE",
        remediation="Move to environment variable AWS_ACCESS_KEY_ID",
        ai_prompt="Remove the hardcoded AWS key on line 14 of app.py and replace with os.environ['AWS_ACCESS_KEY_ID']",
        evidence="AKIAIOSFODNN7EXAMPLE",
        tool="detect-secrets",
    ),
    Finding(
        title="GitHub Token in Config",
        severity=Severity.HIGH,
        category=Category.SECRET,
        file="config.py",
        line=8,
        description="GitHub personal access token found in configuration file",
        remediation="Move to environment variable and add config.py to .gitignore",
        ai_prompt="Replace GITHUB_TOKEN = 'ghp_xxxx...' with os.environ.get('GITHUB_TOKEN')",
        evidence="ghp_ABCDEFghijklmnop1234567890",
        tool="detect-secrets",
    ),

    # ── HALLUCINATED DEPENDENCY (2) ────────────────────────────────
    Finding(
        title="Hallucinated Package: flask-security-utils",
        severity=Severity.CRITICAL,
        category=Category.HALLUCINATED_DEPENDENCY,
        file="requirements.txt",
        line=3,
        description="Package 'flask-security-utils' does not exist on PyPI (HTTP 404). Likely hallucinated by LLM.",
        remediation="Remove flask-security-utils and use flask-security or flask-login instead",
        ai_prompt="Replace 'flask-security-utils' in requirements.txt with 'flask-security-too' which is the real maintained fork",
        evidence="https://pypi.org/pypi/flask-security-utils/json → 404",
        tool="dependency-checker",
    ),
    Finding(
        title="Suspicious Package: reqeusts (typosquat?)",
        severity=Severity.MEDIUM,
        category=Category.HALLUCINATED_DEPENDENCY,
        file="requirements.txt",
        line=7,
        description="Package 'reqeusts' has Levenshtein distance 1 from popular package 'requests'. Possible typosquat.",
        remediation="Verify package name — did you mean 'requests'?",
        ai_prompt="Fix typo in requirements.txt: change 'reqeusts' to 'requests'",
        evidence="Levenshtein distance to 'requests' = 1",
        tool="dependency-checker",
    ),

    # ── SAST (3) ───────────────────────────────────────────────────
    Finding(
        title="SQL Injection via f-string",
        severity=Severity.CRITICAL,
        category=Category.SAST,
        file="app.py",
        line=42,
        description="User input interpolated directly into SQL query using f-string",
        remediation="Use parameterized queries: cursor.execute('SELECT * FROM users WHERE id = %s', (user_id,))",
        ai_prompt="Refactor the SQL query on line 42 of app.py to use parameterized queries instead of f-string interpolation",
        cwe="CWE-89",
        evidence='f"SELECT * FROM users WHERE id = {user_id}"',
        tool="semgrep",
    ),
    Finding(
        title="Use of eval()",
        severity=Severity.HIGH,
        category=Category.SAST,
        file="utils/parser.py",
        line=23,
        description="eval() called with potentially untrusted input",
        remediation="Replace eval() with ast.literal_eval() or a proper parser",
        ai_prompt="Replace eval(data) on line 23 with ast.literal_eval(data) or json.loads(data)",
        cwe="CWE-95",
        evidence="result = eval(user_input)",
        tool="bandit",
    ),
    Finding(
        title="Broad CORS Configuration",
        severity=Severity.MEDIUM,
        category=Category.SAST,
        file="app.py",
        line=8,
        description="CORS configured with origins='*', allowing any domain",
        remediation="Restrict CORS to specific trusted origins",
        ai_prompt="Change CORS(app, origins='*') to CORS(app, origins=['https://yourdomain.com'])",
        cwe="CWE-942",
        tool="semgrep",
    ),

    # ── COMPLIANCE (3) ────────────────────────────────────────────
    Finding(
        title="PII Logged to stdout",
        severity=Severity.HIGH,
        category=Category.COMPLIANCE_GDPR,
        file="routes/users.py",
        line=55,
        description="User email address printed to logs via print() statement",
        remediation="Remove PII from log output or use a PII-safe logger",
        ai_prompt="Remove print(f'Processing {user.email}') on line 55 and replace with logger.info('Processing user %s', user.id)",
        compliance_ref="GDPR Art. 5(1)(f)",
        tool="semgrep",
    ),
    Finding(
        title="No Auth Middleware on Route",
        severity=Severity.HIGH,
        category=Category.COMPLIANCE_SOC2,
        file="routes/admin.py",
        line=12,
        description="Admin route /admin/users has no authentication decorator",
        remediation="Add @login_required or Depends(get_current_user) decorator",
        ai_prompt="Add @login_required decorator above the /admin/users route handler on line 12",
        compliance_ref="SOC2 CC6.1",
        tool="semgrep",
    ),
    Finding(
        title="Missing Data Retention Policy",
        severity=Severity.MEDIUM,
        category=Category.COMPLIANCE_GDPR,
        file=None,
        line=None,
        description="No data deletion mechanism found. App stores user data without apparent retention limits.",
        remediation="Implement user data deletion endpoint and scheduled cleanup",
        ai_prompt="Add a DELETE /api/users/{id} endpoint that removes all user PII and a scheduled task to purge inactive accounts after 2 years",
        compliance_ref="GDPR Art. 17",
        tool="llm-compliance",
        confidence=0.8,
    ),

    # ── PROMPT INJECTION (2) ──────────────────────────────────────
    Finding(
        title="User Input in LLM Prompt",
        severity=Severity.HIGH,
        category=Category.PROMPT_INJECTION,
        file="services/ai.py",
        line=31,
        description="User-supplied text concatenated directly into OpenAI API prompt via f-string",
        remediation="Sanitize user input, use system/user message separation, add output validation",
        ai_prompt="Refactor the OpenAI call on line 31: move the system instructions to the system message role and place user input only in the user message role",
        cwe="CWE-77",
        evidence='f"Analyze this: {user_query}"',
        tool="semgrep",
    ),
    Finding(
        title="LLM Output Passed to eval()",
        severity=Severity.CRITICAL,
        category=Category.PROMPT_INJECTION,
        file="services/ai.py",
        line=48,
        description="LLM response is passed directly to eval() — remote code execution via prompt injection",
        remediation="Never eval() LLM output. Parse it as JSON with json.loads() and validate schema.",
        ai_prompt="Replace eval(response.choices[0].message.content) with json.loads() and add schema validation with pydantic",
        cwe="CWE-94",
        evidence="result = eval(completion.choices[0].message.content)",
        tool="semgrep",
        confidence=0.95,
    ),

    # ── CODE QUALITY (1) ──────────────────────────────────────────
    Finding(
        title="DEBUG Mode Enabled",
        severity=Severity.LOW,
        category=Category.CODE_QUALITY,
        file="config.py",
        line=3,
        description="DEBUG = True set in production configuration file",
        remediation="Set DEBUG = False for production, use environment variable",
        ai_prompt="Change DEBUG = True to DEBUG = os.environ.get('DEBUG', 'false').lower() == 'true'",
        tool="semgrep",
    ),

    # ── LLM REVIEW (2) ───────────────────────────────────────────
    Finding(
        title="Executive Summary",
        severity=Severity.INFO,
        category=Category.LLM_REVIEW,
        description="This repository has critical security gaps: hardcoded secrets, SQL injection, and prompt injection vulnerabilities. The hallucinated dependency 'flask-security-utils' poses a supply chain risk. Immediate remediation required before production deployment.",
        remediation="Address all CRITICAL findings first, then HIGH, before next deployment.",
        ai_prompt="Fix all critical findings in this order: (1) remove hardcoded secrets, (2) parameterize SQL queries, (3) remove eval() of LLM output, (4) replace hallucinated packages",
        tool="llm-summarizer",
    ),
    Finding(
        title="Remediation: Secure the AI Pipeline",
        severity=Severity.INFO,
        category=Category.LLM_REVIEW,
        description="The AI service layer needs input sanitization, output validation, and proper message role separation.",
        remediation="Implement input/output guardrails for all LLM interactions",
        ai_prompt="Refactor services/ai.py: (1) Add input sanitization function, (2) Separate system/user messages, (3) Validate LLM output with JSON schema before use, (4) Add rate limiting",
        tool="llm-summarizer",
    ),
]
